name: formio_flutter
description: A flutter package to let users consume any form created with formIO.js
version: 0.0.1
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.2+2
  device_info: ^0.4.2+9
  image: ^2.1.18
  math_expressions: ^2.0.1
  location: ^3.0.2
  file_picker: ^2.0.10
  intl: ^0.16.1
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      some_platform:
        pluginClass: somePluginClass