name: formio_flutter
description: A flutter package to let users consume any form created with formIO.js
version: 0.9.22
homepage: https://github.com/Crdzbird/formio_flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  provider: ^4.3.2+2
  rxdart: ^0.24.1
  http: ^0.12.2
  image: ^2.1.19
  math_expressions: ^2.0.1
  file_picker: ^2.1.1
  flutter_neumorphic: ^3.0.3
  font_awesome_flutter: ^8.10.0
  universal_io: ^1.0.1
  intl: ^0.16.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any